global:
  name: my-elasticsearch
  namespace: elasticsearch
  esVersion: "7.10.1"

deployment:
  serviceName: elasticsearch
  volumeClaimTemplates:
    storage: 10Gi
    storageClassName: standard
  containers:
    images: "docker.elastic.co/elasticsearch/elasticsearch:7.10.1"
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  clusterNodes: "my-elasticsearch-0,my-elasticsearch-1,my-elasticsearch-2"
